### ISSUE TITLE
build-in https-module limit length

### ISSUE THREAD

**Issue by MyZeD** [sagi/workers-kv#21]
The maximum length of the build-in https-module you use, is ~80Kb.
So you can't upload kv-values over this sum.

This includes the header and body.

https://stackoverflow.com/questions/32763165/node-js-http-get-url-length-limitation
https://github.com/nodejs/http-parser/blob/main/http_parser.h#L55

And i just wondered, why i cant upload my files to KV.

**Comment by sagi** [comment]
Thanks @MyZeD . Strange, back in the day I used this library to upload binary chunks of over 1mb to workers kv. Can you please share a code sample so I can reproduce it? What node version are you using?

**Comment by MyZeD** [comment]
The value ist cutting down on my documents.
The Documents i try to put on KV is a business-thing, so i cant help you with it. (I'm sorry :()
But i JSON.stringify a variable (So its normal String/UTF-8).

My Node Version is v14.18.2
