### ISSUE TITLE
This module requires the presence of "debug"

### ISSUE THREAD

**Issue by glynnbird** [sagi/workers-kv#28]
If I create the very simplest project:

```js
const WorkersKVREST = require('@sagi.io/workers-kv')
const cfAccountId = process.env.CLOUDFLARE_ACCOUNT_ID;
const cfAuthToken = process.env.CLOUDFLARE_AUTH_TOKEN;
const cfEmail = process.env.CLOUDFLARE_EMAIL;
const kv = new WorkersKVREST({ cfAccountId, cfAuthToken, cfEmail })

const main = async () => {
  const r = await kv.listNamespaces()
  console.log(r)
}

main()
```

with `@sagi.io/workers-kv` as my only dependency in package.json, the code fails with:

```
> kvbackup@1.0.0 start
> node index.js

node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'debug'
```

Adding the `debug` module with `npm install --save debug` fixes the problem, but should this module include debug as one of its dependencies if it needs it to be there?

(it's a dev-dependency, but probably needs to be full dependency)

**Comment by sagi** [comment]
@glynnbird Thanks for the heads-up! I've commented it out for now and uploaded the updated version to NPM, as it was only needed for API development
